import { MODULE_NAME } from './constants'

export const INIT_GAMEPLAY = `${MODULE_NAME}/INIT_GAMEPLAY`
export const ADD_SCORE_TO_FRAME = `${MODULE_NAME}/ADD_SCORE_TO_FRAME`
export const UPDATE_STATUS = `${MODULE_NAME}/UPDATE_STATUS`
