import { MODULE_NAME } from './constants'

export const INIT_GAMEPLAY = `${MODULE_NAME}/INIT_GAMEPLAY`
export const SET_ACTIVE_PLAYER_ID = `${MODULE_NAME}/SET_ACTIVE_PLAYER_ID`
export const SET_ACTIVE_FRAME_NUMBER = `${MODULE_NAME}/SET_ACTIVE_FRAME_NUMBER`
export const SET_ACTIVE_ROLL_INDEX = `${MODULE_NAME}/SET_ACTIVE_ROLL_INDEX`
export const ROLL_STARTED = `${MODULE_NAME}/ROLL_STARTED`
export const ROLL_FINISHED = `${MODULE_NAME}/ROLL_FINISHED`
