import { MODULE_NAME } from './constants'

export const ADD_PLAYER = `${MODULE_NAME}/ADD_PLAYER`
export const REMOVE_PLAYER = `${MODULE_NAME}/REMOVE_PLAYER`
export const CHANGE_PLAYERS_ORDER = `${MODULE_NAME}/CHANGE_PLAYERS_ORDER`
